In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
df = pd.read_csv("C:/Users/Priya/Desktop/Factory-Reallocation-Optimization/data/prepared_data.csv")

model = joblib.load("C:/Users/Priya/Desktop/Factory-Reallocation-Optimization/models/best_model.pkl")
scaler = joblib.load("scaler.pkl")
label_encoders = joblib.load("label_encoders.pkl")

In [3]:
factory_coordinates = {
    "Lot's O' Nuts": (32.881893, -111.768036),
    "Wicked Choccy's": (32.076176, -81.088371),
    "Sugar Shack": (48.119140, -96.181150),
    "Secret Factory": (41.446333, -90.565487),
    "The Other Factory": (35.117500, -89.971107)
}

In [4]:
from math import radians, sin, cos, sqrt, atan2

def haversine(lat1, lon1, lat2, lon2):

    R = 6371

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2-lat1
    dlon = lon2-lon1

    a = (
        sin(dlat/2)**2 +
        cos(lat1)*cos(lat2)*sin(dlon/2)**2
    )

    c = 2*atan2(
        sqrt(a),
        sqrt(1-a)
    )

    return R*c

In [5]:
products = df["Product Name"].unique()

print(products)

['Wonka Bar - Milk Chocolate' 'Wonka Bar - Triple Dazzle Caramel'
 'Wonka Bar - Nutty Crunch Surprise' 'Wonka Bar -Scrumdiddlyumptious'
 'Wonka Bar - Fudge Mallows' 'Wonka Gum' 'Kazookles' 'Lickable Wallpaper'
 'Fizzy Lifting Drinks' 'Laffy Taffy' 'SweeTARTS' 'Hair Toffee'
 'Everlasting Gobstopper' 'Fun Dip' 'Nerds']

In [6]:
factory_list = list(factory_coordinates.keys())

print(factory_list)

["Lot's O' Nuts", "Wicked Choccy's", 'Sugar Shack', 'Secret Factory', 'The Other Factory']

In [7]:
recommendations = []

In [8]:
for product in products:

    # Get all orders for this product
    product_data = df[df["Product Name"] == product].copy()

    # Use the first order as a representative sample
    sample = product_data.iloc[0]

    current_factory = sample["Factory"]

    print(f"\nProduct: {product}")
    print(f"Current Factory: {current_factory}")

Product: Wonka Bar - Milk Chocolate
Current Factory: Wicked Choccy's

Product: Wonka Bar - Triple Dazzle Caramel
Current Factory: Wicked Choccy's

Product: Wonka Bar - Nutty Crunch Surprise
Current Factory: Lot's O' Nuts

Product: Wonka Bar -Scrumdiddlyumptious
Current Factory: Lot's O' Nuts

Product: Wonka Bar - Fudge Mallows
Current Factory: Lot's O' Nuts

Product: Wonka Gum
Current Factory: Secret Factory

Product: Kazookles
Current Factory: The Other Factory

Product: Lickable Wallpaper
Current Factory: Secret Factory

Product: Fizzy Lifting Drinks
Current Factory: Sugar Shack

Product: Laffy Taffy
Current Factory: Sugar Shack

Product: SweeTARTS
Current Factory: Sugar Shack

Product: Hair Toffee
Current Factory: The Other Factory

Product: Everlasting Gobstopper
Current Factory: Secret Factory

Product: Fun Dip
Current Factory: Sugar Shack

Product: Nerds
Current Factory: Sugar Shack

In [9]:
for product in products:

    product_data = df[df["Product Name"] == product].copy()

    sample = product_data.iloc[0]

    current_factory = sample["Factory"]

    for factory in factory_list:

        print(product, " ---> ", factory)

Wonka Bar - Milk Chocolate  --->  Lot's O' Nuts
Wonka Bar - Milk Chocolate  --->  Wicked Choccy's
Wonka Bar - Milk Chocolate  --->  Sugar Shack
Wonka Bar - Milk Chocolate  --->  Secret Factory
Wonka Bar - Milk Chocolate  --->  The Other Factory
Wonka Bar - Triple Dazzle Caramel  --->  Lot's O' Nuts
Wonka Bar - Triple Dazzle Caramel  --->  Wicked Choccy's
Wonka Bar - Triple Dazzle Caramel  --->  Sugar Shack
Wonka Bar - Triple Dazzle Caramel  --->  Secret Factory
Wonka Bar - Triple Dazzle Caramel  --->  The Other Factory
Wonka Bar - Nutty Crunch Surprise  --->  Lot's O' Nuts
Wonka Bar - Nutty Crunch Surprise  --->  Wicked Choccy's
Wonka Bar - Nutty Crunch Surprise  --->  Sugar Shack
Wonka Bar - Nutty Crunch Surprise  --->  Secret Factory
Wonka Bar - Nutty Crunch Surprise  --->  The Other Factory
Wonka Bar -Scrumdiddlyumptious  --->  Lot's O' Nuts
Wonka Bar -Scrumdiddlyumptious  --->  Wicked Choccy's
Wonka Bar -Scrumdiddlyumptious  --->  Sugar Shack
Wonka Bar -Scrumdiddlyumptious  --->  Secret Factory
Wonka Bar -Scrumdiddlyumptious  --->  The Other Factory
Wonka Bar - Fudge Mallows  --->  Lot's O' Nuts
Wonka Bar - Fudge Mallows  --->  Wicked Choccy's
Wonka Bar - Fudge Mallows  --->  Sugar Shack
Wonka Bar - Fudge Mallows  --->  Secret Factory
Wonka Bar - Fudge Mallows  --->  The Other Factory
Wonka Gum  --->  Lot's O' Nuts
Wonka Gum  --->  Wicked Choccy's
Wonka Gum  --->  Sugar Shack
Wonka Gum  --->  Secret Factory
Wonka Gum  --->  The Other Factory
Kazookles  --->  Lot's O' Nuts
Kazookles  --->  Wicked Choccy's
Kazookles  --->  Sugar Shack
Kazookles  --->  Secret Factory
Kazookles  --->  The Other Factory
Lickable Wallpaper  --->  Lot's O' Nuts
Lickable Wallpaper  --->  Wicked Choccy's
Lickable Wallpaper  --->  Sugar Shack
Lickable Wallpaper  --->  Secret Factory
Lickable Wallpaper  --->  The Other Factory
Fizzy Lifting Drinks  --->  Lot's O' Nuts
Fizzy Lifting Drinks  --->  Wicked Choccy's
Fizzy Lifting Drinks  --->  Sugar Shack
Fizzy Lifting Drinks  --->  Secret Factory
Fizzy Lifting Drinks  --->  The Other Factory
Laffy Taffy  --->  Lot's O' Nuts
Laffy Taffy  --->  Wicked Choccy's
Laffy Taffy  --->  Sugar Shack
Laffy Taffy  --->  Secret Factory
Laffy Taffy  --->  The Other Factory
SweeTARTS  --->  Lot's O' Nuts
SweeTARTS  --->  Wicked Choccy's
SweeTARTS  --->  Sugar Shack
SweeTARTS  --->  Secret Factory
SweeTARTS  --->  The Other Factory
Hair Toffee  --->  Lot's O' Nuts
Hair Toffee  --->  Wicked Choccy's
Hair Toffee  --->  Sugar Shack
Hair Toffee  --->  Secret Factory
Hair Toffee  --->  The Other Factory
Everlasting Gobstopper  --->  Lot's O' Nuts
Everlasting Gobstopper  --->  Wicked Choccy's
Everlasting Gobstopper  --->  Sugar Shack
Everlasting Gobstopper  --->  Secret Factory
Everlasting Gobstopper  --->  The Other Factory
Fun Dip  --->  Lot's O' Nuts
Fun Dip  --->  Wicked Choccy's
Fun Dip  --->  Sugar Shack
Fun Dip  --->  Secret Factory
Fun Dip  --->  The Other Factory
Nerds  --->  Lot's O' Nuts
Nerds  --->  Wicked Choccy's
Nerds  --->  Sugar Shack
Nerds  --->  Secret Factory
Nerds  --->  The Other Factory

In [10]:
new_row = sample.copy()

In [11]:
new_row["Factory"] = factory

In [12]:
new_row["Factory Latitude"] = factory_coordinates[factory][0]

new_row["Factory Longitude"] = factory_coordinates[factory][1]

In [13]:
new_distance = haversine(
    new_row["Factory Latitude"],
    new_row["Factory Longitude"],
    new_row["Customer Latitude"],
    new_row["Customer Longitude"]
)

new_row["Shipping Distance (km)"] = new_distance

In [14]:
print(
    product,
    "|",
    factory,
    "| Distance:",
    round(new_distance, 2)
)

Nerds | The Other Factory | Distance: 1414.06

In [15]:
for product in products:

    product_data = df[df["Product Name"] == product].copy()

    sample = product_data.iloc[0]

    current_factory = sample["Factory"]

    for factory in factory_list:

        new_row = sample.copy()

        new_row["Factory"] = factory

        new_row["Factory Latitude"] = factory_coordinates[factory][0]
        new_row["Factory Longitude"] = factory_coordinates[factory][1]

        new_distance = haversine(
            new_row["Factory Latitude"],
            new_row["Factory Longitude"],
            new_row["Customer Latitude"],
            new_row["Customer Longitude"]
        )

        new_row["Shipping Distance (km)"] = new_distance

        print(
            product,
            "|",
            factory,
            "| Distance:",
            round(new_distance, 2)
        )

Wonka Bar - Milk Chocolate | Lot's O' Nuts | Distance: 1591.52
Wonka Bar - Milk Chocolate | Wicked Choccy's | Distance: 1386.43
Wonka Bar - Milk Chocolate | Sugar Shack | Distance: 2039.67
Wonka Bar - Milk Chocolate | Secret Factory | Distance: 1367.28
Wonka Bar - Milk Chocolate | The Other Factory | Distance: 780.62
Wonka Bar - Triple Dazzle Caramel | Lot's O' Nuts | Distance: 2298.22
Wonka Bar - Triple Dazzle Caramel | Wicked Choccy's | Distance: 1244.92
Wonka Bar - Triple Dazzle Caramel | Sugar Shack | Distance: 947.64
Wonka Bar - Triple Dazzle Caramel | Secret Factory | Distance: 202.33
Wonka Bar - Triple Dazzle Caramel | The Other Factory | Distance: 753.81
Wonka Bar - Nutty Crunch Surprise | Lot's O' Nuts | Distance: 2298.22
Wonka Bar - Nutty Crunch Surprise | Wicked Choccy's | Distance: 1244.92
Wonka Bar - Nutty Crunch Surprise | Sugar Shack | Distance: 947.64
Wonka Bar - Nutty Crunch Surprise | Secret Factory | Distance: 202.33
Wonka Bar - Nutty Crunch Surprise | The Other Factory | Distance: 753.81
Wonka Bar -Scrumdiddlyumptious | Lot's O' Nuts | Distance: 2298.22
Wonka Bar -Scrumdiddlyumptious | Wicked Choccy's | Distance: 1244.92
Wonka Bar -Scrumdiddlyumptious | Sugar Shack | Distance: 947.64
Wonka Bar -Scrumdiddlyumptious | Secret Factory | Distance: 202.33
Wonka Bar -Scrumdiddlyumptious | The Other Factory | Distance: 753.81
Wonka Bar - Fudge Mallows | Lot's O' Nuts | Distance: 2254.63
Wonka Bar - Fudge Mallows | Wicked Choccy's | Distance: 871.69
Wonka Bar - Fudge Mallows | Sugar Shack | Distance: 1338.26
Wonka Bar - Fudge Mallows | Secret Factory | Distance: 475.52
Wonka Bar - Fudge Mallows | The Other Factory | Distance: 370.56
Wonka Gum | Lot's O' Nuts | Distance: 3166.31
Wonka Gum | Wicked Choccy's | Distance: 824.99
Wonka Gum | Sugar Shack | Distance: 1844.04
Wonka Gum | Secret Factory | Distance: 1174.56
Wonka Gum | The Other Factory | Distance: 1205.83
Kazookles | Lot's O' Nuts | Distance: 1692.12
Kazookles | Wicked Choccy's | Distance: 1182.6
Kazookles | Sugar Shack | Distance: 1747.07
Kazookles | Secret Factory | Distance: 1029.62
Kazookles | The Other Factory | Distance: 446.95
Lickable Wallpaper | Lot's O' Nuts | Distance: 2320.86
Lickable Wallpaper | Wicked Choccy's | Distance: 1249.27
Lickable Wallpaper | Sugar Shack | Distance: 946.6
Lickable Wallpaper | Secret Factory | Distance: 223.49
Lickable Wallpaper | The Other Factory | Distance: 774.19
Fizzy Lifting Drinks | Lot's O' Nuts | Distance: 2339.11
Fizzy Lifting Drinks | Wicked Choccy's | Distance: 1232.66
Fizzy Lifting Drinks | Sugar Shack | Distance: 965.46
Fizzy Lifting Drinks | Secret Factory | Distance: 243.14
Fizzy Lifting Drinks | The Other Factory | Distance: 773.15
Laffy Taffy | Lot's O' Nuts | Distance: 2854.27
Laffy Taffy | Wicked Choccy's | Distance: 201.78
Laffy Taffy | Sugar Shack | Distance: 2330.65
Laffy Taffy | Secret Factory | Distance: 1470.75
Laffy Taffy | The Other Factory | Distance: 940.39
SweeTARTS | Lot's O' Nuts | Distance: 3291.77
SweeTARTS | Wicked Choccy's | Distance: 971.69
SweeTARTS | Sugar Shack | Distance: 1878.01
SweeTARTS | Secret Factory | Distance: 1264.65
SweeTARTS | The Other Factory | Distance: 1352.16
Hair Toffee | Lot's O' Nuts | Distance: 90.0
Hair Toffee | Wicked Choccy's | Distance: 2868.95
Hair Toffee | Sugar Shack | Distance: 2068.35
Hair Toffee | Secret Factory | Distance: 2058.76
Hair Toffee | The Other Factory | Distance: 2010.92
Everlasting Gobstopper | Lot's O' Nuts | Distance: 2610.55
Everlasting Gobstopper | Wicked Choccy's | Distance: 350.61
Everlasting Gobstopper | Sugar Shack | Distance: 2210.2
Everlasting Gobstopper | Secret Factory | Distance: 1346.82
Everlasting Gobstopper | The Other Factory | Distance: 744.39
Fun Dip | Lot's O' Nuts | Distance: 2339.11
Fun Dip | Wicked Choccy's | Distance: 1232.66
Fun Dip | Sugar Shack | Distance: 965.46
Fun Dip | Secret Factory | Distance: 243.14
Fun Dip | The Other Factory | Distance: 773.15
Nerds | Lot's O' Nuts | Distance: 3346.21
Nerds | Wicked Choccy's | Distance: 1031.1
Nerds | Sugar Shack | Distance: 1899.52
Nerds | Secret Factory | Distance: 1308.39
Nerds | The Other Factory | Distance: 1414.06

In [16]:
features = [
    'Ship Mode',
    'Division',
    'Region',
    'Product Name',
    'Factory',
    'Shipping Distance (km)',
    'Sales',
    'Units',
    'Cost',
    'Gross Profit',
    'Profit Margin'
]

In [17]:
def predict_lead_time(new_row):

    # Create a one-row DataFrame
    sample_df = pd.DataFrame([new_row])

    # Keep only training features
    sample_df = sample_df[features]

    # Encode categorical columns
    categorical_columns = [
        'Ship Mode',
        'Division',
        'Region',
        'Product Name',
        'Factory'
    ]

    for col in categorical_columns:
        sample_df[col] = label_encoders[col].transform(
            sample_df[col].astype(str)
        )

    # Scale numerical columns
    numeric_columns = [
        'Shipping Distance (km)',
        'Sales',
        'Units',
        'Cost',
        'Gross Profit',
        'Profit Margin'
    ]

    sample_df[numeric_columns] = scaler.transform(
        sample_df[numeric_columns]
    )

    # Predict lead time
    prediction = model.predict(sample_df)[0]

    return prediction

In [18]:
predicted_lead_time = predict_lead_time(new_row)

print("Predicted Lead Time:", round(predicted_lead_time, 2), "days")

Predicted Lead Time: 1435.39 days

In [19]:
recommendations = []

for product in products:

    product_data = df[df["Product Name"] == product].copy()

    sample = product_data.iloc[0]

    current_factory = sample["Factory"]

    current_prediction = predict_lead_time(sample)

    for factory in factory_list:

        new_row = sample.copy()

        new_row["Factory"] = factory

        new_row["Factory Latitude"] = factory_coordinates[factory][0]
        new_row["Factory Longitude"] = factory_coordinates[factory][1]

        distance = haversine(
            new_row["Factory Latitude"],
            new_row["Factory Longitude"],
            new_row["Customer Latitude"],
            new_row["Customer Longitude"]
        )

        new_row["Shipping Distance (km)"] = distance

        predicted = predict_lead_time(new_row)

        recommendations.append({
            "Product": product,
            "Current Factory": current_factory,
            "Recommended Factory": factory,
            "Current Lead Time": current_prediction,
            "Predicted Lead Time": predicted,
            "Shipping Distance (km)": distance,
            "Lead Time Improvement": current_prediction - predicted,
            "Profit Margin": sample["Profit Margin"]
        })

In [20]:
recommendation_df = pd.DataFrame(recommendations)

recommendation_df.head()

,Product,Current Factory,Recommended Factory,Current Lead Time,Predicted Lead Time,Shipping Distance (km),Lead Time Improvement,Profit Margin
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,1311.973111,1305.498078,1591.518335,6.475033,0.649231
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,1311.973111,1311.973111,1386.426875,0.000000,0.649231
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,1311.973111,1362.726364,2039.674858,-50.753253,0.649231
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,1311.973111,1309.295212,1367.281304,2.677899,0.649231
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,1311.973111,1367.186860,780.624908,-55.213749,0.649231

In [21]:
recommendation_df["Optimization Score"] = (
    recommendation_df["Lead Time Improvement"] * 0.60
    - recommendation_df["Shipping Distance (km)"] * 0.0002
    + recommendation_df["Profit Margin"] * 0.15
)

In [22]:
recommendation_df = recommendation_df.sort_values(
    ["Product", "Optimization Score"],
    ascending=[True, False]
)

In [23]:
best_recommendations = (
    recommendation_df
    .groupby("Product")
    .head(1)
    .reset_index(drop=True)
)

In [24]:
best_recommendations[
    [
        "Product",
        "Current Factory",
        "Recommended Factory",
        "Current Lead Time",
        "Predicted Lead Time",
        "Lead Time Improvement",
        "Shipping Distance (km)",
        "Optimization Score"
    ]
]

,Product,Current Factory,Recommended Factory,Current Lead Time,Predicted Lead Time,Lead Time Improvement,Shipping Distance (km),Optimization Score
0,Everlasting Gobstopper,Secret Factory,Sugar Shack,1312.218365,1308.547600,3.670765,2210.204939,1.880418
1,Fizzy Lifting Drinks,Sugar Shack,Secret Factory,1264.852132,1202.405573,62.446558,243.137323,37.509307
2,Fun Dip,Sugar Shack,Lot's O' Nuts,1259.084089,1229.227975,29.856115,2339.110762,17.505847
3,Hair Toffee,The Other Factory,Lot's O' Nuts,1308.421013,1122.525551,185.895461,89.999432,111.635944
4,Kazookles,The Other Factory,The Other Factory,1129.245956,1129.245956,0.000000,446.953572,-0.077852
5,Laffy Taffy,Sugar Shack,The Other Factory,1212.692221,1202.927165,9.765056,940.388475,5.764423
6,Lickable Wallpaper,Secret Factory,Secret Factory,1194.433374,1194.433374,0.000000,223.491816,0.030302
7,Nerds,Sugar Shack,Secret Factory,1443.771034,1402.474833,41.296201,1308.391943,24.586042
8,SweeTARTS,Sugar Shack,Secret Factory,1372.055647,1326.302854,45.752793,1264.648579,27.268746
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,Sugar Shack,1302.738229,1295.010394,7.727835,1338.258283,4.469049
10,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,1311.973111,1305.498078,6.475033,1591.518335,3.664101
11,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Wicked Choccy's,1320.143381,1302.528086,17.615295,1244.923655,10.427213
12,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Wicked Choccy's,1302.528086,1302.528086,0.000000,1244.923655,-0.150985
13,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,Wicked Choccy's,1311.545424,1296.348298,15.197127,1244.923655,8.973458
14,Wonka Gum,Secret Factory,Wicked Choccy's,1325.515579,1243.972987,81.542593,824.990419,48.838558

In [25]:
best_recommendations.to_csv(
    "factory_recommendations.csv",
    index=False
)

print("Factory recommendations saved successfully!")

Factory recommendations saved successfully!

In [26]:
best_recommendations.head()

,Product,Current Factory,Recommended Factory,Current Lead Time,Predicted Lead Time,Shipping Distance (km),Lead Time Improvement,Profit Margin,Optimization Score
0,Everlasting Gobstopper,Secret Factory,Sugar Shack,1312.218365,1308.547600,2210.204939,3.670765,0.800000,1.880418
1,Fizzy Lifting Drinks,Sugar Shack,Secret Factory,1264.852132,1202.405573,243.137323,62.446558,0.600000,37.509307
2,Fun Dip,Sugar Shack,Lot's O' Nuts,1259.084089,1229.227975,2339.110762,29.856115,0.400000,17.505847
3,Hair Toffee,The Other Factory,Lot's O' Nuts,1308.421013,1122.525551,89.999432,185.895461,0.777778,111.635944
4,Kazookles,The Other Factory,The Other Factory,1129.245956,1129.245956,446.953572,0.000000,0.076923,-0.077852

In [27]:
recommendations = []

In [28]:
product_factory_map = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

In [30]:
recommendations = []

for product in products:

    product_orders = df[df["Product Name"] == product]

    current_factory = product_factory_map[product]

    for factory in factory_list:

        lead_times = []
        distances = []
        profit_margins = []

        for _, row in product_orders.iterrows():

            new_row = row.copy()

            new_row["Factory"] = factory

            new_row["Factory Latitude"] = factory_coordinates[factory][0]
            new_row["Factory Longitude"] = factory_coordinates[factory][1]

            distance = haversine(
                new_row["Factory Latitude"],
                new_row["Factory Longitude"],
                new_row["Customer Latitude"],
                new_row["Customer Longitude"]
            )

            new_row["Shipping Distance (km)"] = distance

            predicted = predict_lead_time(new_row)

            lead_times.append(predicted)
            distances.append(distance)
            profit_margins.append(new_row["Profit Margin"])

        recommendations.append({

            "Product": product,

            "Current Factory": current_factory,

            "Factory": factory,

            "Average Lead Time": np.mean(lead_times),

            "Average Distance": np.mean(distances),

            "Average Profit Margin": np.mean(profit_margins)

        })

In [31]:
recommendation_df = pd.DataFrame(recommendations)

recommendation_df.head()

,Product,Current Factory,Factory,Average Lead Time,Average Distance,Average Profit Margin
0,Wonka Bar - Milk Chocolate,Wicked Choccy's,Lot's O' Nuts,1318.603988,1981.554715,0.649231
1,Wonka Bar - Milk Chocolate,Wicked Choccy's,Wicked Choccy's,1320.123048,1924.640474,0.649231
2,Wonka Bar - Milk Chocolate,Wicked Choccy's,Sugar Shack,1332.241162,1858.546104,0.649231
3,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,1322.359688,1531.140638,0.649231
4,Wonka Bar - Milk Chocolate,Wicked Choccy's,The Other Factory,1331.274790,1551.962983,0.649231

In [32]:
from sklearn.preprocessing import MinMaxScaler

score_scaler = MinMaxScaler()

recommendation_df[
    [
        "LeadTimeScore",
        "DistanceScore",
        "ProfitScore"
    ]
] = score_scaler.fit_transform(

    recommendation_df[
        [
            "Average Lead Time",
            "Average Distance",
            "Average Profit Margin"
        ]
    ]

)

In [33]:
recommendation_df["Optimization Score"] = (

    (1 - recommendation_df["LeadTimeScore"]) * 0.50 +

    (1 - recommendation_df["DistanceScore"]) * 0.30 +

    recommendation_df["ProfitScore"] * 0.20

)

In [34]:
recommendation_df = recommendation_df.sort_values(
    ["Product", "Optimization Score"],
    ascending=[True, False]
)

In [35]:
best_recommendations = (

    recommendation_df
    .groupby("Product")
    .first()
    .reset_index()

)

best_recommendations

,Product,Current Factory,Factory,Average Lead Time,Average Distance,Average Profit Margin,LeadTimeScore,DistanceScore,ProfitScore,Optimization Score
0,Everlasting Gobstopper,Secret Factory,The Other Factory,1370.583747,957.296762,0.800000,0.708953,0.147093,1.000000,0.601396
1,Fizzy Lifting Drinks,Sugar Shack,Secret Factory,1288.120358,1125.587853,0.600000,0.381017,0.207177,0.723404,0.692019
2,Fun Dip,Sugar Shack,Secret Factory,1274.386067,545.303107,0.400000,0.326399,0.000000,0.446809,0.726162
3,Hair Toffee,The Other Factory,Lot's O' Nuts,1298.309789,1199.121464,0.777778,0.421538,0.233431,0.969267,0.713055
4,Kazookles,The Other Factory,Wicked Choccy's,1192.309127,1969.061460,0.076923,0.000000,0.508320,0.000000,0.647504
5,Laffy Taffy,Sugar Shack,Wicked Choccy's,1316.029347,1324.140470,0.623116,0.492004,0.278066,0.755373,0.621653
6,Lickable Wallpaper,Secret Factory,Secret Factory,1312.934475,1522.632030,0.500000,0.479696,0.348933,0.585106,0.572493
7,Nerds,Sugar Shack,Wicked Choccy's,1416.046038,1031.103147,0.466667,0.889745,0.173444,0.539007,0.410896
8,SweeTARTS,Sugar Shack,The Other Factory,1366.914309,1264.033588,0.466667,0.694360,0.256606,0.539007,0.483639
9,Wonka Bar - Fudge Mallows,Lot's O' Nuts,Secret Factory,1321.364666,1534.857244,0.666667,0.513221,0.353298,0.815603,0.600521
10,Wonka Bar - Milk Chocolate,Wicked Choccy's,Secret Factory,1322.359688,1531.140638,0.649231,0.517178,0.351971,0.791489,0.594118
11,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,Secret Factory,1327.003408,1516.440763,0.713467,0.535645,0.346722,0.880327,0.604226
12,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,Secret Factory,1323.358681,1544.282728,0.653333,0.521151,0.356663,0.797163,0.591858
13,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,Secret Factory,1322.947097,1551.655371,0.694444,0.519514,0.359295,0.854019,0.603258
14,Wonka Gum,Secret Factory,Secret Factory,1316.821672,1379.313260,0.520000,0.495155,0.297764,0.612766,0.585647